import type { Order, Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "X-Bacon Especial",
    category: "Lanches",
    description: "Pão, hambúrguer 160g, queijo, bacon e molho da casa.",
    price: 29.9,
    active: true,
    featured: true,
    emoji: "🍔",
  },
  {
    id: 2,
    name: "X-Salada",
    category: "Lanches",
    description: "Hambúrguer, queijo, salada fresca e maionese.",
    price: 24.9,
    active: true,
    emoji: "🥪",
  },
  {
    id: 3,
    name: "Pizza Calabresa",
    category: "Pizzas",
    description: "Molho, muçarela, calabresa, cebola e orégano.",
    price: 49.9,
    active: true,
    featured: true,
    emoji: "🍕",
  },
  {
    id: 4,
    name: "Pizza Frango c/ Catupiry",
    category: "Pizzas",
    description: "Frango desfiado, catupiry e muçarela.",
    price: 54.9,
    active: true,
    emoji: "🍕",
  },
  {
    id: 5,
    name: "Batata Grande",
    category: "Porções",
    description: "Batata crocante com molho especial.",
    price: 22.0,
    active: true,
    emoji: "🍟",
  },
  {
    id: 6,
    name: "Coca-Cola 2L",
    category: "Bebidas",
    description: "Refrigerante gelado.",
    price: 14.0,
    active: true,
    emoji: "🥤",
  },
  {
    id: 7,
    name: "Suco de Laranja",
    category: "Bebidas",
    description: "500ml, feito na hora.",
    price: 12.0,
    active: true,
    emoji: "🍊",
  },
  {
    id: 8,
    name: "Brownie",
    category: "Sobremesas",
    description: "Chocolate meio amargo e cobertura cremosa.",
    price: 13.9,
    active: false,
    emoji: "🍫",
  },
];

export const orders: Order[] = [
  {
    id: "#1048",
    customer: "Mariana Silva",
    phone: "(17) 99722-4108",
    total: 78.8,
    payment: "Pix",
    type: "Delivery",
    status: "Recebido",
    time: "17:42",
    address: "Rua Brasil, 218 — Centro",
    courier: "João",
    items: [
      { name: "X-Bacon Especial", qty: 2, price: 29.9 },
      { name: "Coca-Cola 2L", qty: 1, price: 14 },
      { name: "Taxa de entrega", qty: 1, price: 5 },
    ],
  },
  {
    id: "#1047",
    customer: "Lucas Mendes",
    phone: "(17) 99131-8031",
    total: 54.9,
    payment: "Crédito",
    type: "Retirada",
    status: "Em preparo",
    time: "17:35",
    items: [{ name: "Pizza Frango c/ Catupiry", qty: 1, price: 54.9 }],
  },
  {
    id: "#1046",
    customer: "Ana Paula",
    phone: "(17) 99610-1174",
    total: 66.9,
    payment: "Dinheiro",
    type: "Mesa",
    status: "Pronto",
    time: "17:28",
    table: "Mesa 07",
    items: [
      { name: "Pizza Calabresa", qty: 1, price: 49.9 },
      { name: "Suco de Laranja", qty: 1, price: 12 },
      { name: "Serviço", qty: 1, price: 5 },
    ],
  },
  {
    id: "#1045",
    customer: "Rafael Costa",
    phone: "(17) 99280-5199",
    total: 43.9,
    payment: "Débito",
    type: "Delivery",
    status: "Entregando",
    time: "17:10",
    address: "Av. dos Expedicionários, 410",
    courier: "Carlos",
    items: [
      { name: "X-Salada", qty: 1, price: 24.9 },
      { name: "Batata Grande", qty: 1, price: 22 },
    ],
  },
  {
    id: "#1044",
    customer: "Fernanda Lima",
    phone: "(17) 98819-3102",
    total: 109.8,
    payment: "Pix",
    type: "Encomenda",
    status: "Finalizado",
    time: "16:48",
    items: [{ name: "Pizza Frango c/ Catupiry", qty: 2, price: 54.9 }],
  },
];

export const customers = [
  {
    name: "Mariana Silva",
    phone: "(17) 99722-4108",
    orders: 18,
    spent: 1284.4,
    last: "Hoje, 17:42",
  },
  {
    name: "Rafael Costa",
    phone: "(17) 99280-5199",
    orders: 12,
    spent: 792.1,
    last: "Hoje, 17:10",
  },
  {
    name: "Ana Paula",
    phone: "(17) 99610-1174",
    orders: 9,
    spent: 623.8,
    last: "Hoje, 17:28",
  },
  {
    name: "Lucas Mendes",
    phone: "(17) 99131-8031",
    orders: 7,
    spent: 431.6,
    last: "Hoje, 17:35",
  },
  {
    name: "Fernanda Lima",
    phone: "(17) 98819-3102",
    orders: 21,
    spent: 1750.2,
    last: "Hoje, 16:48",
  },
];

export const couriers = [
  {
    name: "João",
    phone: "(17) 99111-2200",
    active: true,
    deliveries: 14,
    fee: 84,
  },
  {
    name: "Carlos",
    phone: "(17) 99222-3300",
    active: true,
    deliveries: 11,
    fee: 66,
  },
  {
    name: "Mateus",
    phone: "(17) 99333-4400",
    active: false,
    deliveries: 7,
    fee: 42,
  },
];
